CPP = CC
OPTFLAGS= -O2 -DMPICH_IGNORE_CXX_SEEK 

INC_HDF5 = -I/usr/local/include
LIB_HDF5 = -L/usr/local/lib
HDF5LIBS = -lm -lhdf5 -lhdf5_hl 


HDF5_2_VTK: HDF5_2_VTK.cpp 
	${CPP} -o  HDF5_2_VTK ${INC_HDF5} ${LIB_HDF5} ${HDF5LIBS} HDF5_2_VTK.cpp 	

HDF5_TestParticles:HDF5_TestParticles.cpp
	${CPP} -o  HDF5_TestParticles ${INC_HDF5} ${LIB_HDF5} ${HDF5LIBS} HDF5_TestParticles.cpp

clean:
	rm -rf   HDF5_2_VTK ProcVDist HDF5_2_VTK_Selected ProcHighVLocation  ProcSampleTraj ProcAllTraj
